spring.application.name=lizieT123
# Configuración del servidor
server.port=8080
# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123
spring.h2.console.enabled=true

# Configuración de Hibernate (JPA)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Inicialización de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configuración JWT
jwt.secret=3cd370be00016b0952db5f3691326fdb125432ce7f70b7baa11ac045b8b64810
jwt.expiration=3600000