INSERT INTO CATEGORIAS (ID_CATEGORIA, DESCRIPCION, NOMBRE) VALUES (1, 'CATEGORIA 1', 'CAT1');
INSERT INTO usuarios (ID, USERNAME, PASSWORD, ROLE) VALUES (1, 'raul', '$2a$10$NE0NwdLV0TTkAEiL3cqqbeBbucGEb0l2QBav9Jm/NhSCZi.O3a3ja', 'admin');
INSERT INTO usuarios (ID, USERNAME, PASSWORD, ROLE) VALUES (2, 'nest', '$2a$10$0SsC3/XDoe69nEAMQSAq3uZJxkCnFVcGzAkbZv74YbG5R2WtmM/gm', 'admin');